gestion_emplois:
    resource: "@GestionEmploisBundle/Resources/config/routing.yml"
    prefix:   /
gestion_user:
    resource: "@GestionUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

user_mailing:
    resource: "@UserCommunicationBundle/Resources/config/routing.yml"
    prefix: /communication
question_reponse:
    resource: "@QuestionReponseQuestionReponseBundle/Resources/config/routing.yml"
    prefix: /question_reponse

